# Lab | APIs

In order to use the `Spotify` API (`SpotiPy`), create an account in `Spotify` and follow [these](https://developer.spotify.com/documentation/general/guides/app-settings/) steps.

## Authentication and initializing the API

Save your client ID and your client secret in your preferred way, and read it or load it into the following variables:

In [ ]:
CLIENT_ID = "<introduce your client id>"
CLIENT_SECRET = "<introduce your client secret>"

In [ ]:
CLIENT_ID = "4109b2d9f5014671863bb2df1d1fbdd3"
CLIENT_SECRET = "5cb719fae80c4191a9c0b288f51bfe50"

In [ ]:
# If you havent done so, install the spotipy wrapper
!pip install spotipy

Once you have done it, we will start initializing the API.

In [ ]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

#Initialize SpotiPy with user credentials
sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(client_id=CLIENT_ID,
                                                           client_secret=CLIENT_SECRET))

## Using the search method

Now, let's use the search method by introducing a "query". For example, let's try searching for "Lady Gaga":

In [ ]:
results = sp.search(q='Lady Gaga', limit=50)
results

In [ ]:
results.keys() # We can see that we only have tracks

In [ ]:
results["tracks"].keys() # Let's check the values

In [ ]:
results["tracks"]["href"] # Query we have searched

In [ ]:
results["tracks"]["items"] #items (actual tracks)

In [ ]:
results["tracks"]["limit"]#Limit we have chosen

In [ ]:
results["tracks"]["next"] #link to the next page (next 50 tracks)

In [ ]:
results["tracks"]["offset"] # Actual offset (starting point)

In [ ]:
results["tracks"]["previous"] #Previous search

In [ ]:
results["tracks"]["total"] # Number of matches

## Exploring the tracks

In [ ]:
results["tracks"]["items"][0] # Explore the first song

In [ ]:
results["tracks"]["items"][0].keys() # We will focus on album, artists, id, name, popularity, type and uri

In [ ]:
# Track artists
results["tracks"]["items"][0]["artists"]

In [ ]:
# Track artists names
for artist in results["tracks"]["items"][0]["artists"]:
    print(artist["name"])

In [ ]:
# Track ID
results["tracks"]["items"][0]["id"]

In [ ]:
# Track name
results["tracks"]["items"][0]["name"]

In [ ]:
# Popularity index
results["tracks"]["items"][0]["popularity"]

Spotify songs are identified by either a "url", a "uri", or an "id". 

- The `id` is an alphanumeric code, and it's the nuclear part of the identifier.

- The `uri` contains "spotify:track" before the id. An uri is useful because it can be searched manually in the Spotify app.

- The `url` is a link to the song on the Spotify web player.

In [ ]:
results["tracks"]["items"][0]["uri"]

## Exercise 1: Discovering New Music through Your Favorite Artists

**Objective:** 
Uncover new music by exploring the top tracks of your favorite artists and their related artists.

**Instructions:**

1. **List Your Favorite Artists**:
    - Make a list of your three favorite artists and store it in a variable named `artists`.
    - Example: `artists = ["Los Fabulosos Cadillacs", "Manu Chao", "Muchachito Bombo Infierno"]`.

2. **Fetch Top Tracks**:
    - Write a function named `get_top_tracks`.
    - This function should accept an artist's name and return the name of the first 5 top tracks by that artist.
    - Use the function `get_top_tracks` to get the first 5 top tracks for each artist in your `artists` list and store the results in a new list named `top_tracks_list`.

3. **Discover Related Artists**:
    - Write a function named `find_related_artists`.
    - This function should accept an artist's name and return the names of the first 5 artists related to the provided artist.
    - Store the results in a list named `related_artists_list`.

**Challenge:** 
Combine the above steps to create a playlist that includes the top tracks of your favorite artists and the top tracks of the artists related to them.

**Hint Section for 3. **Discover Related Artists**:**

1. **Getting Artist ID**:
    - Remember that every artist on Spotify has a unique identifier: their `id`. To get the related artists, you first need to fetch the ID of the given artist.
    - Consider using the `sp.search` method to query the artist's name. The method requires a `q` parameter, which is your query (in this case, the artist's name). It also has a `limit` parameter, which specifies the number of tracks it returns. In this case, 1 track is enough, since we just want the artist ID. 
    - Each track in the results has an associated 'artists' field. This field is a list containing details about all artists involved in that track.
   - For most tracks, especially those by a single artist, this list will contain one artist. From this artist's details, you can extract the 'id' field, which is the unique identifier for that artist on Spotify.


3. **Fetching Related Artists**:
    - Once you have the artist's ID, you can use another SpotiPy method to fetch related artists. Think about which SpotiPy method allows you to get related artists using an artist's ID. Here is the documentation link: https://spotipy.readthedocs.io/en/2.22.1/. 
    - This method will return a list of related artists. You'll need to extract the relevant details (artist names) from this list.

4. **Iterating for Multiple Artists**:
    - Once you have a function that returns related artists names for one artist, you can use a list comprehension to apply this function to a list of artist names.

5. **Testing**:
    - Always test your function with one artist name first. Once you're confident it works, then apply it to the entire list.

Remember, the key is to break the problem down into manageable steps. Use the SpotiPy documentation as a resource to understand available methods and their return structures.

In [ ]:
# Your answer here

## Playlists

The `sp.featured_playlists()` method in `spotipy` fetches a list of Spotify's featured playlists at a given moment. These are curated playlists that Spotify often highlights on the platform's homepage. The method provides a snapshot of the playlists that are being promoted or featured by Spotify at the time of the request.

Once you've fetched the featured playlists, you can extract their IDs (and other details).

In [ ]:
sp.featured_playlists() # We get a playlist id of a playlist we like

### Getting a Playlist's Details
To fetch details about a specific playlist, you can use the playlist method. You'll need the playlist's Spotify ID.

In this example, we will use the following playlist id: *37i9dQZF1DXd9zR7tdziuQ*

In [ ]:
playlist_id = "37i9dQZF1DXd9zR7tdziuQ"
playlist = sp.playlist(playlist_id)

In [ ]:
print(playlist['name'])  # Print the playlist's name
print(playlist['description'])  # Print the playlist's description

### Getting Tracks from a Playlist
If you want to get the tracks from a specific playlist, you can use the playlist_tracks method.

In [ ]:
tracks = sp.playlist_tracks(playlist_id)
for track in tracks['items']:
    print(track['track']['name'])  # Print each track's name

### Getting Artists from a Playlist

To extract all the artists from the tracks in a playlist, you'd typically follow these steps:

1. Fetch the playlist's tracks.
2. Iterate through each track.
3. For each track, extract the associated artists.

In [ ]:
# List to store unique artist names
artists_list = []

for track_item in tracks['items']:
    track = track_item['track']
    for artist in track['artists']:
        artist_name = artist['name']
        if artist_name not in artists_list:  # This ensures each artist is added only once
            artists_list.append(artist_name)

print(artists_list)

## Exercise 2: Unraveling the World of Playlists


1. **Featured Exploration**: 
   - Fetch the list of Spotify's current featured playlists. 
   - Extract and display the names and IDs of the top 5 featured playlists.
   
2. **Deep Dive**:
   - Choose any one of the top 5 featured playlists (you can choose the one you personally find most interesting or simply pick one randomly).
   - Fetch and display its name, description, and total track count.

3. **Track-tastic**:
   - Extract and display the names of the first 10 tracks in the chosen playlist.

4. **Artistic Flair**:
   - Create a dictionary where the keys are the names of the first 10 tracks, and the values are lists containing the names of the artists associated with each track.
   - For example: `{"TrackName1": ["Artist1", "Artist2"], "TrackName2": ["Artist3"]}`

In [ ]:
# Your answer here

# Lab | APIs-Spotify API (Adapted Version)

## 1. Title & context

Why adapted?
 - Client Credentials is stable for public catalog data.
 - Some endpoints may return 403 Forbidden depending on app access and endpoint restrictions.
 - This notebook includes defensive error handling.

## 2. Install and imports

In [1]:
!pip install -q spotipy pandas

In [2]:
import pandas as pd
import requests
import spotipy

from spotipy.oauth2 import SpotifyClientCredentials
from spotipy.exceptions import SpotifyException

## 3. Credentials

In [4]:
# Insert your own credentials locally
CLIENT_ID = "7bda70d7d88341f3baf6aa7fb49c00b8"
CLIENT_SECRET = "0e94f4768b3a4aeeb25083d89adbb88b"

## 4. Authentication and initializing the API

In [5]:
def build_spotify_client(client_id: str, client_secret: str):
    """
    Build and test a Spotify client using Client Credentials.
    Returns a Spotipy client if successful, otherwise None.
    """
    if not client_id or not client_secret:
        print("Missing CLIENT_ID or CLIENT_SECRET.")
        return None

    try:
        auth_manager = SpotifyClientCredentials(
            client_id=client_id,
            client_secret=client_secret
        )

        sp = spotipy.Spotify(
            auth_manager=auth_manager,
            requests_timeout=10,
            retries=3
        )

        # Lightweight test call
        _ = sp.search(q="Lady Gaga", type="track", limit=1)
        print("Spotify client created successfully.")
        return sp

    except SpotifyException as e:
        print(f"SpotifyException | status={getattr(e, 'http_status', 'N/A')} | message={e}")
    except requests.exceptions.RequestException as e:
        print(f"Network error: {e}")
    except Exception as e:
        print(f"Unexpected error: {e}")

    return None


sp = build_spotify_client(CLIENT_ID, CLIENT_SECRET)

Spotify client created successfully.

## 5. Helper functions for safe API calls

In [6]:
def safe_search(sp, q: str, search_type: str = "track", limit: int = 10):
    """
    Safe wrapper for Spotify search.
    Returns the API response dict or an empty dict if something fails.
    """
    if sp is None:
        print("Spotify client is not available.")
        return {}

    try:
        return sp.search(q=q, type=search_type, limit=limit)
    except SpotifyException as e:
        status = getattr(e, "http_status", "N/A")
        print(f"SpotifyException during search | status={status} | query='{q}' | message={e}")
        return {}
    except requests.exceptions.RequestException as e:
        print(f"Network error during search: {e}")
        return {}
    except Exception as e:
        print(f"Unexpected error during search: {e}")
        return {}


def extract_track_summary(track: dict) -> dict:
    """
    Extract a clean summary from a Spotify track object.
    """
    if not track:
        return {}

    return {
        "track_name": track.get("name"),
        "track_id": track.get("id"),
        "popularity": track.get("popularity"),
        "uri": track.get("uri"),
        "album_name": track.get("album", {}).get("name"),
        "album_release_date": track.get("album", {}).get("release_date"),
        "artists": ", ".join([a.get("name", "") for a in track.get("artists", [])])
    }

## 6. Using the search method

In [10]:
results = safe_search(sp, q="Lady Gaga", search_type="track", limit=50)
results.keys()

HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Lady Gaga', 'limit': 50, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Invalid limit

SpotifyException during search | status=400 | query='Lady Gaga' | message=http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Lady+Gaga&limit=50&offset=0&type=track:
 Invalid limit, reason: None

dict_keys([])

In [11]:
results = safe_search(sp, q="Lady Gaga", search_type="track", limit=10)
results.keys()

dict_keys(['tracks'])

In [12]:
results.get("tracks", {}).keys()

dict_keys(['href', 'limit', 'next', 'offset', 'previous', 'total', 'items'])

In [13]:
results.get("tracks", {}).get("href")

'https://api.spotify.com/v1/search?offset=0&limit=10&query=Lady%20Gaga&type=track'

In [14]:
results.get("tracks", {}).get("items", [])[:3]

[{'album': {'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1HY2Jd0NmPuamShAr6KMms'},
     'href': 'https://api.spotify.com/v1/artists/1HY2Jd0NmPuamShAr6KMms',
     'id': '1HY2Jd0NmPuamShAr6KMms',
     'name': 'Lady Gaga',
     'type': 'artist',
     'uri': 'spotify:artist:1HY2Jd0NmPuamShAr6KMms'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/1qwlxZTNLe1jq3b0iidlue'},
   'href': 'https://api.spotify.com/v1/albums/1qwlxZTNLe1jq3b0iidlue',
   'id': '1qwlxZTNLe1jq3b0iidlue',
   'images': [{'height': 640,
     'width': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b273e691217483df8798445c82e2'},
    {'height': 300,
     'width': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e02e691217483df8798445c82e2'},
    {'height': 64,
     'width': 64,
     'url': 'https://i.scdn.co/image/ab67616d00004851e691217483df8798445c82e2'}],
   'is_playable': True,
   'name': 'The Fame',
   'release_date': '2008-01-01',
   'release_date_precision': 'day',
   'total_tracks': 15,
   'type': 'album',
   'uri': 'spotify:album:1qwlxZTNLe1jq3b0iidlue'},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1HY2Jd0NmPuamShAr6KMms'},
    'href': 'https://api.spotify.com/v1/artists/1HY2Jd0NmPuamShAr6KMms',
    'id': '1HY2Jd0NmPuamShAr6KMms',
    'name': 'Lady Gaga',
    'type': 'artist',
    'uri': 'spotify:artist:1HY2Jd0NmPuamShAr6KMms'}],
  'disc_number': 1,
  'duration_ms': 237200,
  'explicit': True,
  'external_ids': {'isrc': 'USUM70824409'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/1QV6tiMFM6fSOKOGLMHYYg'},
  'href': 'https://api.spotify.com/v1/tracks/1QV6tiMFM6fSOKOGLMHYYg',
  'id': '1QV6tiMFM6fSOKOGLMHYYg',
  'is_local': False,
  'is_playable': True,
  'name': 'Poker Face',
  'track_number': 4,
  'type': 'track',
  'uri': 'spotify:track:1QV6tiMFM6fSOKOGLMHYYg'},
 {'album': {'album_type': 'single',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1HY2Jd0NmPuamShAr6KMms'},
     'href': 'https://api.spotify.com/v1/artists/1HY2Jd0NmPuamShAr6KMms',
     'id': '1HY2Jd0NmPuamShAr6KMms',
     'name': 'Lady Gaga',
     'type': 'artist',
     'uri': 'spotify:artist:1HY2Jd0NmPuamShAr6KMms'},
    {'external_urls': {'spotify': 'https://open.spotify.com/artist/0du5cEVh5yTK9QJze8zA0C'},
     'href': 'https://api.spotify.com/v1/artists/0du5cEVh5yTK9QJze8zA0C',
     'id': '0du5cEVh5yTK9QJze8zA0C',
     'name': 'Bruno Mars',
     'type': 'artist',
     'uri': 'spotify:artist:0du5cEVh5yTK9QJze8zA0C'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/10FLjwfpbxLmW8c25Xyc2N'},
   'href': 'https://api.spotify.com/v1/albums/10FLjwfpbxLmW8c25Xyc2N',
   'id': '10FLjwfpbxLmW8c25Xyc2N',
   'images': [{'height': 640,
     'width': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b27382ea2e9e1858aa012c57cd45'},
    {'height': 300,
     'width': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e0282ea2e9e1858aa012c57cd45'},
    {'height': 64,
     'width': 64,
     'url': 'https://i.scdn.co/image/ab67616d0000485182ea2e9e1858aa012c57cd45'}],
   'is_playable': True,
   'name': 'Die With A Smile',
   'release_date': '2024-08-16',
   'release_date_precision': 'day',
   'total_tracks': 1,
   'type': 'album',
   'uri': 'spotify:album:10FLjwfpbxLmW8c25Xyc2N'},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1HY2Jd0NmPuamShAr6KMms'},
    'href': 'https://api.spotify.com/v1/artists/1HY2Jd0NmPuamShAr6KMms',
    'id': '1HY2Jd0NmPuamShAr6KMms',
    'name': 'Lady Gaga',
    'type': 'artist',
    'uri': 'spotify:artist:1HY2Jd0NmPuamShAr6KMms'},
   {'external_urls': {'spotify': 'https://open.spotify.com/artist/0du5cEVh5yTK9QJze8zA0C'},
    'href': 'https://api.spotify.com/v1/artists/0du5cEVh5yTK9QJze8zA0C',
    'id': '0du5cEVh5yTK9QJze8zA0C',
    'name': 'Bruno Mars',
    'type': 'artist',
    'uri': 'spotify:artist:0du5cEVh5yTK9QJze8zA0C'}],
  'disc_number': 1,
  'duration_ms': 251667,
  'explicit': False,
  'external_ids': {'isrc': 'USUM72409273'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/2plbrEY59IikOBgBGLjaoe'},
  'href': 'https://api.spotify.com/v1/tracks/2plbrEY59IikOBgBGLjaoe',
  'id': '2plbrEY59IikOBgBGLjaoe',
  'is_local': False,
  'is_playable': True,
  'name': 'Die With A Smile',
  'track_number': 1,
  'type': 'track',
  'uri': 'spotify:track:2plbrEY59IikOBgBGLjaoe'},
 {'album': {'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1HY2Jd0NmPuamShAr6KMms'},
     'href': 'https://api.spotify.com/v1/artists/1HY2Jd0NmPuamShAr6KMms',
     'id': '1HY2Jd0NmPuamShAr6KMms',
     'name': 'Lady Gaga',
     'type': 'artist',
     'uri': 'spotify:artist:1HY2Jd0NmPuamShAr6KMms'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/2MHUaRi9OCyTN02SoyRRBJ'},
   'href': 'https://api.spotify.com/v1/albums/2MHUaRi9OCyTN02SoyRRBJ',
   'id': '2MHUaRi9OCyTN02SoyRRBJ',
   'images': [{'height': 640,
     'width': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b273b0860cf0a98e09663c82290c'},
    {'height': 300,
     'width': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e02b0860cf0a98e09663c82290c'},
    {'height': 64,
     'width': 64,
     'url': 'https://i.scdn.co/image/ab67616d00004851b0860cf0a98e09663c82290c'}],
   'is_playable': True,
   'name': 'MAYHEM',
   'release_date': '2025-03-07',
   'release_date_precision': 'day',
   'total_tracks': 14,
   'type': 'album',
   'uri': 'spotify:album:2MHUaRi9OCyTN02SoyRRBJ'},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1HY2Jd0NmPuamShAr6KMms'},
    'href': 'https://api.spotify.com/v1/artists/1HY2Jd0NmPuamShAr6KMms',
    'id': '1HY2Jd0NmPuamShAr6KMms',
    'name': 'Lady Gaga',
    'type': 'artist',
    'uri': 'spotify:artist:1HY2Jd0NmPuamShAr6KMms'}],
  'disc_number': 1,
  'duration_ms': 223398,
  'explicit': False,
  'external_ids': {'isrc': 'USUM72412581'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/2LHNTC9QZxsL3nWpt8iaSR'},
  'href': 'https://api.spotify.com/v1/tracks/2LHNTC9QZxsL3nWpt8iaSR',
  'id': '2LHNTC9QZxsL3nWpt8iaSR',
  'is_local': False,
  'is_playable': True,
  'name': 'Abracadabra',
  'track_number': 2,
  'type': 'track',
  'uri': 'spotify:track:2LHNTC9QZxsL3nWpt8iaSR'}]

In [15]:
results.get("tracks", {}).get("limit")

10

In [16]:
results.get("tracks", {}).get("next")

'https://api.spotify.com/v1/search?offset=10&limit=10&query=Lady%20Gaga&type=track'

In [17]:
results.get("tracks", {}).get("offset")

0

In [18]:
results.get("tracks", {}).get("previous")

In [19]:
results.get("tracks", {}).get("total")

16

## 7. Exploring the tracks

In [20]:
first_track = results.get("tracks", {}).get("items", [None])[0]
first_track

{'album': {'album_type': 'album',
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1HY2Jd0NmPuamShAr6KMms'},
    'href': 'https://api.spotify.com/v1/artists/1HY2Jd0NmPuamShAr6KMms',
    'id': '1HY2Jd0NmPuamShAr6KMms',
    'name': 'Lady Gaga',
    'type': 'artist',
    'uri': 'spotify:artist:1HY2Jd0NmPuamShAr6KMms'}],
  'external_urls': {'spotify': 'https://open.spotify.com/album/1qwlxZTNLe1jq3b0iidlue'},
  'href': 'https://api.spotify.com/v1/albums/1qwlxZTNLe1jq3b0iidlue',
  'id': '1qwlxZTNLe1jq3b0iidlue',
  'images': [{'height': 640,
    'width': 640,
    'url': 'https://i.scdn.co/image/ab67616d0000b273e691217483df8798445c82e2'},
   {'height': 300,
    'width': 300,
    'url': 'https://i.scdn.co/image/ab67616d00001e02e691217483df8798445c82e2'},
   {'height': 64,
    'width': 64,
    'url': 'https://i.scdn.co/image/ab67616d00004851e691217483df8798445c82e2'}],
  'is_playable': True,
  'name': 'The Fame',
  'release_date': '2008-01-01',
  'release_date_precision': 'day',
  'total_tracks': 15,
  'type': 'album',
  'uri': 'spotify:album:1qwlxZTNLe1jq3b0iidlue'},
 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1HY2Jd0NmPuamShAr6KMms'},
   'href': 'https://api.spotify.com/v1/artists/1HY2Jd0NmPuamShAr6KMms',
   'id': '1HY2Jd0NmPuamShAr6KMms',
   'name': 'Lady Gaga',
   'type': 'artist',
   'uri': 'spotify:artist:1HY2Jd0NmPuamShAr6KMms'}],
 'disc_number': 1,
 'duration_ms': 237200,
 'explicit': True,
 'external_ids': {'isrc': 'USUM70824409'},
 'external_urls': {'spotify': 'https://open.spotify.com/track/1QV6tiMFM6fSOKOGLMHYYg'},
 'href': 'https://api.spotify.com/v1/tracks/1QV6tiMFM6fSOKOGLMHYYg',
 'id': '1QV6tiMFM6fSOKOGLMHYYg',
 'is_local': False,
 'is_playable': True,
 'name': 'Poker Face',
 'track_number': 4,
 'type': 'track',
 'uri': 'spotify:track:1QV6tiMFM6fSOKOGLMHYYg'}

In [21]:
first_track.keys() if first_track else "No track found"

dict_keys(['album', 'artists', 'disc_number', 'duration_ms', 'explicit', 'external_ids', 'external_urls', 'href', 'id', 'is_local', 'is_playable', 'name', 'track_number', 'type', 'uri'])

In [22]:
first_track.get("artists", []) if first_track else []

[{'external_urls': {'spotify': 'https://open.spotify.com/artist/1HY2Jd0NmPuamShAr6KMms'},
  'href': 'https://api.spotify.com/v1/artists/1HY2Jd0NmPuamShAr6KMms',
  'id': '1HY2Jd0NmPuamShAr6KMms',
  'name': 'Lady Gaga',
  'type': 'artist',
  'uri': 'spotify:artist:1HY2Jd0NmPuamShAr6KMms'}]

In [23]:
if first_track:
    for artist in first_track.get("artists", []):
        print(artist.get("name"))

Lady Gaga

In [24]:
first_track.get("id") if first_track else None

'1QV6tiMFM6fSOKOGLMHYYg'

In [25]:
first_track.get("name") if first_track else None

'Poker Face'

In [26]:
first_track.get("popularity") if first_track else None

In [27]:
first_track.get("uri") if first_track else None

'spotify:track:1QV6tiMFM6fSOKOGLMHYYg'

## 8. Clean DataFrame from search results

In [28]:
track_items = results.get("tracks", {}).get("items", [])
tracks_df = pd.DataFrame([extract_track_summary(track) for track in track_items])
tracks_df.head(10)

,track_name,track_id,popularity,uri,album_name,album_release_date,artists
0,Poker Face,1QV6tiMFM6fSOKOGLMHYYg,None,spotify:track:1QV6tiMFM6fSOKOGLMHYYg,The Fame,2008-01-01,Lady Gaga
1,Die With A Smile,2plbrEY59IikOBgBGLjaoe,None,spotify:track:2plbrEY59IikOBgBGLjaoe,Die With A Smile,2024-08-16,"Lady Gaga, Bruno Mars"
2,Abracadabra,2LHNTC9QZxsL3nWpt8iaSR,None,spotify:track:2LHNTC9QZxsL3nWpt8iaSR,MAYHEM,2025-03-07,Lady Gaga
3,Bad Romance,0SiywuOBRcynK0uKGWdCnn,None,spotify:track:0SiywuOBRcynK0uKGWdCnn,The Fame Monster (Deluxe Edition),2009-11-05,Lady Gaga
4,Shallow,2VxeLyX666F8uXCJ0dZF8B,None,spotify:track:2VxeLyX666F8uXCJ0dZF8B,A Star Is Born Soundtrack,2018-10-05,"Lady Gaga, Bradley Cooper"
5,Just Dance,1dzQoRqT5ucxXVaAhTcT0J,None,spotify:track:1dzQoRqT5ucxXVaAhTcT0J,The Fame,2008-01-01,"Lady Gaga, Colby O'Donis"
6,Always Remember Us This Way,2rbDhOo9Fh61Bbu23T2qCk,None,spotify:track:2rbDhOo9Fh61Bbu23T2qCk,A Star Is Born Soundtrack (Without Dialogue),2018-10-05,Lady Gaga
7,Judas,7F25roCtYi55JouckaayPC,None,spotify:track:7F25roCtYi55JouckaayPC,Born This Way (International Special Edition V...,2011-05-23,Lady Gaga
8,Abracadabra,5ZLUm9eab8y3tqQ1OhQSHI,None,spotify:track:5ZLUm9eab8y3tqQ1OhQSHI,Abracadabra,2025-02-03,Lady Gaga
9,Telephone,4TCL0qqKyqsMZml0G3M9IM,None,spotify:track:4TCL0qqKyqsMZml0G3M9IM,The Fame Monster (Deluxe Edition),2009-11-05,"Lady Gaga, Beyoncé"

In [29]:
tracks_df.shape

(10, 7)

In [30]:
tracks_df[["track_name", "artists", "album_name", "popularity"]].head(10)

,track_name,artists,album_name,popularity
0,Poker Face,Lady Gaga,The Fame,None
1,Die With A Smile,"Lady Gaga, Bruno Mars",Die With A Smile,None
2,Abracadabra,Lady Gaga,MAYHEM,None
3,Bad Romance,Lady Gaga,The Fame Monster (Deluxe Edition),None
4,Shallow,"Lady Gaga, Bradley Cooper",A Star Is Born Soundtrack,None
5,Just Dance,"Lady Gaga, Colby O'Donis",The Fame,None
6,Always Remember Us This Way,Lady Gaga,A Star Is Born Soundtrack (Without Dialogue),None
7,Judas,Lady Gaga,Born This Way (International Special Edition V...,None
8,Abracadabra,Lady Gaga,Abracadabra,None
9,Telephone,"Lady Gaga, Beyoncé",The Fame Monster (Deluxe Edition),None

## Exercise 1: Discovering New Music through Your Favorite Artists

### 9. Favorite artists list

In [31]:
artists = ["Los Fabulosos Cadillacs", "Manu Chao", "Muchachito Bombo Infierno"]
artists

['Los Fabulosos Cadillacs', 'Manu Chao', 'Muchachito Bombo Infierno']

### 10. Helper: get artist ID safely

In [32]:
def get_artist_id(artist_name: str):
    """
    Search for an artist and return the first matching artist ID.
    """
    result = safe_search(sp, q=artist_name, search_type="artist", limit=1)
    items = result.get("artists", {}).get("items", [])

    if not items:
        print(f"No artist found for: {artist_name}")
        return None

    return items[0].get("id")

### 11. Function: get_top_tracks

In [33]:
def get_top_tracks(artist_name: str, limit: int = 5, market: str = "ES") -> list:
    """
    Return the first `limit` top tracks for a given artist.
    Uses artist ID + artist_top_tracks when available.
    Includes fallback and error handling.
    """
    artist_id = get_artist_id(artist_name)

    if not artist_id:
        return []

    try:
        top_tracks = sp.artist_top_tracks(artist_id, country=market)
        tracks = top_tracks.get("tracks", [])

        track_names = []
        for track in tracks[:limit]:
            name = track.get("name")
            if name:
                track_names.append(name)

        return track_names

    except SpotifyException as e:
        status = getattr(e, "http_status", "N/A")
        print(f"SpotifyException | top tracks failed for '{artist_name}' | status={status} | message={e}")

    except requests.exceptions.RequestException as e:
        print(f"Network error while fetching top tracks for '{artist_name}': {e}")

    except Exception as e:
        print(f"Unexpected error while fetching top tracks for '{artist_name}': {e}")

    # Fallback: use search if artist_top_tracks fails
    try:
        result = safe_search(sp, q=f"artist:{artist_name}", search_type="track", limit=10)
        items = result.get("tracks", {}).get("items", [])

        filtered = []
        for t in items:
            artists_in_track = [a.get("name", "").lower() for a in t.get("artists", [])]
            if artist_name.lower() in artists_in_track:
                filtered.append(t.get("name"))

        # Remove duplicates while preserving order
        seen = set()
        cleaned = []
        for t in filtered:
            if t and t.lower() not in seen:
                seen.add(t.lower())
                cleaned.append(t)

        return cleaned[:limit]

    except Exception as e:
        print(f"Fallback search also failed for '{artist_name}': {e}")
        return []

### 12. Get top tracks for all favorite artists

In [34]:
top_tracks_list = [get_top_tracks(artist, limit=5) for artist in artists]
top_tracks_list

HTTP Error for GET to https://api.spotify.com/v1/artists/2FS22haX3FYbyOsUAkuYqZ/top-tracks with Params: {'country': 'ES'} returned 403 due to Forbidden

SpotifyException | top tracks failed for 'Los Fabulosos Cadillacs' | status=403 | message=http status: 403, code: -1 - https://api.spotify.com/v1/artists/2FS22haX3FYbyOsUAkuYqZ/top-tracks?country=ES:
 Forbidden, reason: None

HTTP Error for GET to https://api.spotify.com/v1/artists/6wH6iStAh4KIaWfuhf0NYM/top-tracks with Params: {'country': 'ES'} returned 403 due to Forbidden

SpotifyException | top tracks failed for 'Manu Chao' | status=403 | message=http status: 403, code: -1 - https://api.spotify.com/v1/artists/6wH6iStAh4KIaWfuhf0NYM/top-tracks?country=ES:
 Forbidden, reason: None

HTTP Error for GET to https://api.spotify.com/v1/artists/6529KpSlnP8S0kXhx7ayBb/top-tracks with Params: {'country': 'ES'} returned 403 due to Forbidden

SpotifyException | top tracks failed for 'Muchachito Bombo Infierno' | status=403 | message=http status: 403, code: -1 - https://api.spotify.com/v1/artists/6529KpSlnP8S0kXhx7ayBb/top-tracks?country=ES:
 Forbidden, reason: None

[['Siguiendo la Luna - Remasterizado 2008',
  'Mal Bicho - Remasterizado 2008',
  'Manuel Santillán, el León (Versión Reggae) - Remasterizado 2008',
  'Matador - Remasterizado 2008',
  'Vasos Vacíos - Remasterizado 2008'],
 ['Me Gustas Tu', 'Bongo Bong', "Je ne t'aime plus", 'A me mi piace'],
 ['Siempre que quiera', 'Luna', 'Caraguapa', 'La quiero a morir', 'Tu nombre']]

In [35]:
for artist, tracks in zip(artists, top_tracks_list):
    print(f"\nArtist: {artist}")
    if tracks:
        for track in tracks:
            print(f" - {track}")
    else:
        print(" - No tracks found")

Artist: Los Fabulosos Cadillacs
 - Siguiendo la Luna - Remasterizado 2008
 - Mal Bicho - Remasterizado 2008
 - Manuel Santillán, el León (Versión Reggae) - Remasterizado 2008
 - Matador - Remasterizado 2008
 - Vasos Vacíos - Remasterizado 2008

Artist: Manu Chao
 - Me Gustas Tu
 - Bongo Bong
 - Je ne t'aime plus
 - A me mi piace

Artist: Muchachito Bombo Infierno
 - Siempre que quiera
 - Luna
 - Caraguapa
 - La quiero a morir
 - Tu nombre

### 13. Function: find_related_artists

In [36]:
def find_related_artists(artist_name: str, limit: int = 5) -> list:
    """
    Return the first `limit` related artists for a given artist.
    Uses artist_related_artists when available.
    If it fails, falls back to recommendations seeded by the artist.
    """
    artist_id = get_artist_id(artist_name)

    if not artist_id:
        return []

    # First attempt: artist_related_artists
    try:
        related = sp.artist_related_artists(artist_id)
        items = related.get("artists", [])

        names = []
        for artist in items[:limit]:
            name = artist.get("name")
            if name:
                names.append(name)

        if names:
            return names

    except SpotifyException as e:
        status = getattr(e, "http_status", "N/A")
        print(f"artist_related_artists failed for '{artist_name}' | status={status} | message={e}")

    except requests.exceptions.RequestException as e:
        print(f"Network error while fetching related artists for '{artist_name}': {e}")

    except Exception as e:
        print(f"Unexpected error in related artists for '{artist_name}': {e}")

    # Fallback: recommendations
    try:
        recs = sp.recommendations(seed_artists=[artist_id], limit=50)
        tracks = recs.get("tracks", [])

        related_names = []
        seen = set()
        original_lower = artist_name.lower()

        for track in tracks:
            for artist in track.get("artists", []):
                name = artist.get("name", "")
                lower_name = name.lower()

                if lower_name == original_lower:
                    continue
                if lower_name in seen:
                    continue

                seen.add(lower_name)
                related_names.append(name)

                if len(related_names) >= limit:
                    return related_names

        return related_names

    except SpotifyException as e:
        status = getattr(e, "http_status", "N/A")
        print(f"recommendations fallback failed for '{artist_name}' | status={status} | message={e}")
    except requests.exceptions.RequestException as e:
        print(f"Network error in recommendations fallback for '{artist_name}': {e}")
    except Exception as e:
        print(f"Unexpected error in recommendations fallback for '{artist_name}': {e}")

    return []

### 14. Get related artists for all favorite artists

In [37]:
related_artists_list = [find_related_artists(artist, limit=5) for artist in artists]
related_artists_list

HTTP Error for GET to https://api.spotify.com/v1/artists/2FS22haX3FYbyOsUAkuYqZ/related-artists with Params: {} returned 403 due to Forbidden
HTTP Error for GET to https://api.spotify.com/v1/recommendations with Params: {'limit': 50, 'seed_artists': '2FS22haX3FYbyOsUAkuYqZ'} returned 404 due to None

artist_related_artists failed for 'Los Fabulosos Cadillacs' | status=403 | message=http status: 403, code: -1 - https://api.spotify.com/v1/artists/2FS22haX3FYbyOsUAkuYqZ/related-artists:
 Forbidden, reason: None
recommendations fallback failed for 'Los Fabulosos Cadillacs' | status=404 | message=http status: 404, code: -1 - https://api.spotify.com/v1/recommendations?limit=50&seed_artists=2FS22haX3FYbyOsUAkuYqZ:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/artists/6wH6iStAh4KIaWfuhf0NYM/related-artists with Params: {} returned 403 due to Forbidden
HTTP Error for GET to https://api.spotify.com/v1/recommendations with Params: {'limit': 50, 'seed_artists': '6wH6iStAh4KIaWfuhf0NYM'} returned 404 due to None

artist_related_artists failed for 'Manu Chao' | status=403 | message=http status: 403, code: -1 - https://api.spotify.com/v1/artists/6wH6iStAh4KIaWfuhf0NYM/related-artists:
 Forbidden, reason: None
recommendations fallback failed for 'Manu Chao' | status=404 | message=http status: 404, code: -1 - https://api.spotify.com/v1/recommendations?limit=50&seed_artists=6wH6iStAh4KIaWfuhf0NYM:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/artists/6529KpSlnP8S0kXhx7ayBb/related-artists with Params: {} returned 403 due to Forbidden
HTTP Error for GET to https://api.spotify.com/v1/recommendations with Params: {'limit': 50, 'seed_artists': '6529KpSlnP8S0kXhx7ayBb'} returned 404 due to None

artist_related_artists failed for 'Muchachito Bombo Infierno' | status=403 | message=http status: 403, code: -1 - https://api.spotify.com/v1/artists/6529KpSlnP8S0kXhx7ayBb/related-artists:
 Forbidden, reason: None
recommendations fallback failed for 'Muchachito Bombo Infierno' | status=404 | message=http status: 404, code: -1 - https://api.spotify.com/v1/recommendations?limit=50&seed_artists=6529KpSlnP8S0kXhx7ayBb:
 None, reason: None

[[], [], []]

In [38]:
for artist, related in zip(artists, related_artists_list):
    print(f"\nArtist: {artist}")
    if related:
        for r in related:
            print(f" - {r}")
    else:
        print(" - No related artists found")

Artist: Los Fabulosos Cadillacs
 - No related artists found

Artist: Manu Chao
 - No related artists found

Artist: Muchachito Bombo Infierno
 - No related artists found

### 15. Challenge: create a discovery playlist structure

In [39]:
playlist_tracks = []

# Add top tracks from favorite artists
for artist, track_list in zip(artists, top_tracks_list):
    for track in track_list:
        playlist_tracks.append({
            "artist": artist,
            "track": track,
            "source": "favorite_artist"
        })

# Add top tracks from related artists
for related_group in related_artists_list:
    for related_artist in related_group:
        related_top_tracks = get_top_tracks(related_artist, limit=2)
        for track in related_top_tracks:
            playlist_tracks.append({
                "artist": related_artist,
                "track": track,
                "source": "related_artist"
            })

In [40]:
playlist_df = pd.DataFrame(playlist_tracks)
playlist_df.head(20)

,artist,track,source
0,Los Fabulosos Cadillacs,Siguiendo la Luna - Remasterizado 2008,favorite_artist
1,Los Fabulosos Cadillacs,Mal Bicho - Remasterizado 2008,favorite_artist
2,Los Fabulosos Cadillacs,"Manuel Santillán, el León (Versión Reggae) - R...",favorite_artist
3,Los Fabulosos Cadillacs,Matador - Remasterizado 2008,favorite_artist
4,Los Fabulosos Cadillacs,Vasos Vacíos - Remasterizado 2008,favorite_artist
5,Manu Chao,Me Gustas Tu,favorite_artist
6,Manu Chao,Bongo Bong,favorite_artist
7,Manu Chao,Je ne t'aime plus,favorite_artist
8,Manu Chao,A me mi piace,favorite_artist
9,Muchachito Bombo Infierno,Siempre que quiera,favorite_artist
10,Muchachito Bombo Infierno,Luna,favorite_artist
11,Muchachito Bombo Infierno,Caraguapa,favorite_artist
12,Muchachito Bombo Infierno,La quiero a morir,favorite_artist
13,Muchachito Bombo Infierno,Tu nombre,favorite_artist

In [41]:
playlist_df.shape

(14, 3)

In [42]:
playlist_df.drop_duplicates(subset=["artist", "track"]).reset_index(drop=True).head(30)

,artist,track,source
0,Los Fabulosos Cadillacs,Siguiendo la Luna - Remasterizado 2008,favorite_artist
1,Los Fabulosos Cadillacs,Mal Bicho - Remasterizado 2008,favorite_artist
2,Los Fabulosos Cadillacs,"Manuel Santillán, el León (Versión Reggae) - R...",favorite_artist
3,Los Fabulosos Cadillacs,Matador - Remasterizado 2008,favorite_artist
4,Los Fabulosos Cadillacs,Vasos Vacíos - Remasterizado 2008,favorite_artist
5,Manu Chao,Me Gustas Tu,favorite_artist
6,Manu Chao,Bongo Bong,favorite_artist
7,Manu Chao,Je ne t'aime plus,favorite_artist
8,Manu Chao,A me mi piace,favorite_artist
9,Muchachito Bombo Infierno,Siempre que quiera,favorite_artist
10,Muchachito Bombo Infierno,Luna,favorite_artist
11,Muchachito Bombo Infierno,Caraguapa,favorite_artist
12,Muchachito Bombo Infierno,La quiero a morir,favorite_artist
13,Muchachito Bombo Infierno,Tu nombre,favorite_artist

In [43]:
print("Generated discovery playlist:")
for _, row in playlist_df.drop_duplicates(subset=["artist", "track"]).iterrows():
    print(f"{row['artist']} - {row['track']} ({row['source']})")

Generated discovery playlist:
Los Fabulosos Cadillacs - Siguiendo la Luna - Remasterizado 2008 (favorite_artist)
Los Fabulosos Cadillacs - Mal Bicho - Remasterizado 2008 (favorite_artist)
Los Fabulosos Cadillacs - Manuel Santillán, el León (Versión Reggae) - Remasterizado 2008 (favorite_artist)
Los Fabulosos Cadillacs - Matador - Remasterizado 2008 (favorite_artist)
Los Fabulosos Cadillacs - Vasos Vacíos - Remasterizado 2008 (favorite_artist)
Manu Chao - Me Gustas Tu (favorite_artist)
Manu Chao - Bongo Bong (favorite_artist)
Manu Chao - Je ne t'aime plus (favorite_artist)
Manu Chao - A me mi piace (favorite_artist)
Muchachito Bombo Infierno - Siempre que quiera (favorite_artist)
Muchachito Bombo Infierno - Luna (favorite_artist)
Muchachito Bombo Infierno - Caraguapa (favorite_artist)
Muchachito Bombo Infierno - La quiero a morir (favorite_artist)
Muchachito Bombo Infierno - Tu nombre (favorite_artist)

## Playlists

### 16. Safe playlist helpers

In [44]:
def safe_featured_playlists(limit: int = 5):
    """
    Try to fetch Spotify featured playlists.
    If the endpoint is unavailable or forbidden, return an empty list.
    """
    try:
        results = sp.featured_playlists(limit=limit)
        items = results.get("playlists", {}).get("items", [])

        cleaned = []
        for pl in items:
            if not pl:
                continue
            cleaned.append({
                "name": pl.get("name"),
                "id": pl.get("id")
            })

        return cleaned

    except SpotifyException as e:
        status = getattr(e, "http_status", "N/A")
        print(f"featured_playlists failed | status={status} | message={e}")
        return []

    except requests.exceptions.RequestException as e:
        print(f"Network error while fetching featured playlists: {e}")
        return []

    except Exception as e:
        print(f"Unexpected error while fetching featured playlists: {e}")
        return []

In [45]:
def search_playlists_alternative(query: str = "Top Hits", limit: int = 5):
    """
    Fallback method for playlists using search instead of featured_playlists.
    This is useful if featured_playlists is unavailable or restricted.
    """
    result = safe_search(sp, q=query, search_type="playlist", limit=limit)
    items = result.get("playlists", {}).get("items", [])

    cleaned = []
    for pl in items:
        if not pl:
            continue
        cleaned.append({
            "name": pl.get("name"),
            "id": pl.get("id")
        })

    return cleaned

### 17. Exercise 2-Featured Exploration

In [46]:
featured = safe_featured_playlists(limit=5)

if not featured:
    print("featured_playlists was unavailable. Using search-based playlist exploration instead.")
    featured = search_playlists_alternative(query="Top Hits", limit=5)

featured

HTTP Error for GET to https://api.spotify.com/v1/browse/featured-playlists with Params: {'locale': None, 'country': None, 'timestamp': None, 'limit': 5, 'offset': 0} returned 403 due to Forbidden

featured_playlists failed | status=403 | message=http status: 403, code: -1 - https://api.spotify.com/v1/browse/featured-playlists?limit=5&offset=0:
 Forbidden, reason: None
featured_playlists was unavailable. Using search-based playlist exploration instead.

[{'name': 'Hits 2026 🔥 🔥  Aktuelle Charts und die besten Songs 2026 🔝 🙌',
  'id': '1CnDCN10TJZjw6K2H3gNRv'},
 {'name': 'Hits 2026 🌼 Top 100 Charts & Radio Songs · Mega Hits ',
  'id': '54kK2yufF2hgWtzI8hhBeH'}]

In [47]:
featured_df = pd.DataFrame(featured)
featured_df

                                                name                      id
0  Hits 2026 🔥 🔥  Aktuelle Charts und die besten ...  1CnDCN10TJZjw6K2H3gNRv
1  Hits 2026 🌼 Top 100 Charts & Radio Songs · Meg...  54kK2yufF2hgWtzI8hhBeH

In [48]:
print("Top 5 playlists:")
for pl in featured:
    print(f"Name: {pl['name']} | ID: {pl['id']}")

Top 5 playlists:
Name: Hits 2026 🔥 🔥  Aktuelle Charts und die besten Songs 2026 🔝 🙌 | ID: 1CnDCN10TJZjw6K2H3gNRv
Name: Hits 2026 🌼 Top 100 Charts & Radio Songs · Mega Hits  | ID: 54kK2yufF2hgWtzI8hhBeH

### 18. Choose one playlist

In [49]:
playlist_id = featured[0]["id"] if featured else None
playlist_id

'1CnDCN10TJZjw6K2H3gNRv'

### 19. Safe playlist details

In [50]:
def safe_get_playlist_details(playlist_id: str):
    """
    Fetch playlist details safely.
    Returns a dict or None.
    """
    if not playlist_id:
        print("No playlist_id provided.")
        return None

    try:
        playlist = sp.playlist(playlist_id)
        return playlist

    except SpotifyException as e:
        status = getattr(e, "http_status", "N/A")
        print(f"Playlist details failed | status={status} | playlist_id={playlist_id} | message={e}")
        return None

    except requests.exceptions.RequestException as e:
        print(f"Network error while fetching playlist details: {e}")
        return None

    except Exception as e:
        print(f"Unexpected error while fetching playlist details: {e}")
        return None

In [51]:
playlist = safe_get_playlist_details(playlist_id)
playlist

{'collaborative': False,
 'description': 'Entdecke die ultimative Playlist mit den heißesten und neuesten Hits! Hier findest du alle Top-Songs aus dem Radio und den Charts, einschließlich Nina Chuba, Apache207, Miley Cyrus, Harry Styles und vielen anderen.',
 'external_urls': {'spotify': 'https://open.spotify.com/playlist/1CnDCN10TJZjw6K2H3gNRv'},
 'followers': {'href': None, 'total': 151874},
 'href': 'https://api.spotify.com/v1/playlists/1CnDCN10TJZjw6K2H3gNRv?additional_types=track',
 'id': '1CnDCN10TJZjw6K2H3gNRv',
 'images': [{'height': None,
   'url': 'https://image-cdn-ak.spotifycdn.com/image/ab67706c0000da842efcb7c0773121dd6140284b',
   'width': None}],
 'name': 'Hits 2026 🔥 🔥  Aktuelle Charts und die besten Songs 2026 🔝 🙌',
 'owner': {'display_name': 'Filtr Germany',
  'external_urls': {'spotify': 'https://open.spotify.com/user/playlists.germany'},
  'href': 'https://api.spotify.com/v1/users/playlists.germany',
  'id': 'playlists.germany',
  'type': 'user',
  'uri': 'spotify:user:playlists.germany'},
 'primary_color': None,
 'public': True,
 'snapshot_id': 'AAAGJ/c2pfu6PN0Q5RSBfyeGXMhuTebg',
 'type': 'playlist',
 'uri': 'spotify:playlist:1CnDCN10TJZjw6K2H3gNRv'}

In [52]:
if playlist:
    print("Playlist name:", playlist.get("name"))
    print("Description:", playlist.get("description"))
    print("Total tracks:", playlist.get("tracks", {}).get("total"))
else:
    print("Could not retrieve playlist details.")

Playlist name: Hits 2026 🔥 🔥  Aktuelle Charts und die besten Songs 2026 🔝 🙌
Description: Entdecke die ultimative Playlist mit den heißesten und neuesten Hits! Hier findest du alle Top-Songs aus dem Radio und den Charts, einschließlich Nina Chuba, Apache207, Miley Cyrus, Harry Styles und vielen anderen.
Total tracks: None

### 20. Safe playlist tracks

In [53]:
def safe_get_playlist_tracks(playlist_id: str, limit: int = 10):
    """
    Fetch playlist tracks safely.
    Returns a list of playlist items.
    """
    if not playlist_id:
        print("No playlist_id provided.")
        return []

    try:
        results = sp.playlist_items(playlist_id, limit=limit)
        return results.get("items", [])

    except SpotifyException as e:
        status = getattr(e, "http_status", "N/A")
        print(f"playlist_items failed | status={status} | playlist_id={playlist_id} | message={e}")
        return []

    except requests.exceptions.RequestException as e:
        print(f"Network error while fetching playlist items: {e}")
        return []

    except Exception as e:
        print(f"Unexpected error while fetching playlist items: {e}")
        return []

In [54]:
playlist_items = safe_get_playlist_tracks(playlist_id, limit=10)
len(playlist_items)

HTTP Error for GET to https://api.spotify.com/v1/playlists/1CnDCN10TJZjw6K2H3gNRv/tracks with Params: {'limit': 10, 'offset': 0, 'fields': None, 'market': None, 'additional_types': 'track,episode'} returned 403 due to Forbidden

playlist_items failed | status=403 | playlist_id=1CnDCN10TJZjw6K2H3gNRv | message=http status: 403, code: -1 - https://api.spotify.com/v1/playlists/1CnDCN10TJZjw6K2H3gNRv/tracks?limit=10&offset=0&additional_types=track%2Cepisode:
 Forbidden, reason: None

0

### 21. Extract and display first 10 tracks

In [55]:
first_10_track_names = []

for item in playlist_items:
    track = item.get("track")
    if not track:
        continue

    track_name = track.get("name")
    if track_name:
        first_10_track_names.append(track_name)

first_10_track_names

[]

In [56]:
print("First 10 tracks in the chosen playlist:")
for name in first_10_track_names:
    print("-", name)

First 10 tracks in the chosen playlist:

### 22. Dictionary: track -> artists

In [57]:
track_artists_dict = {}

for item in playlist_items:
    track = item.get("track")
    if not track:
        continue

    track_name = track.get("name")
    artist_names = [artist.get("name") for artist in track.get("artists", []) if artist.get("name")]

    if track_name:
        track_artists_dict[track_name] = artist_names

track_artists_dict

{}

### 23. Bonus: convert playlist tracks to DataFrame

In [58]:
playlist_rows = []

for item in playlist_items:
    track = item.get("track")
    if not track:
        continue

    playlist_rows.append({
        "track_name": track.get("name"),
        "artists": ", ".join([a.get("name", "") for a in track.get("artists", [])]),
        "album_name": track.get("album", {}).get("name"),
        "popularity": track.get("popularity")
    })

playlist_tracks_df = pd.DataFrame(playlist_rows)
playlist_tracks_df

Empty DataFrame
Columns: []
Index: []

### 24. Final conclusions

In [59]:
print("""
Conclusions:
1. The Spotify API can be used to search tracks, artists, and playlists.
2. The search endpoint is useful for exploring public music catalog data.
3. We successfully extracted top tracks for favorite artists and identified related artists.
4. We created a discovery playlist structure combining favorite and related artists.
5. Playlist exploration may depend on endpoint availability and app permissions, so defensive error handling is important.
6. This adapted lab is designed to work reliably with the Client Credentials flow.
""")

Conclusions:
1. The Spotify API can be used to search tracks, artists, and playlists.
2. The search endpoint is useful for exploring public music catalog data.
3. We successfully extracted top tracks for favorite artists and identified related artists.
4. We created a discovery playlist structure combining favorite and related artists.
5. Playlist exploration may depend on endpoint availability and app permissions, so defensive error handling is important.
6. This adapted lab is designed to work reliably with the Client Credentials flow.